import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav/Nav'
import MainPageIcon from '../components/MainPageIcon/MainPageIcon'
import axios from 'axios'
import MainPageAds from '../components/MainPageAds/MainPageAds'
import { NavContext } from '../contexts/navcontext'
import React, { useEffect } from 'react'

export default function Home({allcategories, allads}) {
const navCtx = React.useContext(NavContext)

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      <nav className='px-10'>
          <Nav />
        </nav>
        <div>
          <hr></hr>
        </div>
      </header>
      <main className="grid justify-center w-full">

        <div className='grid w-full justify-center'>
        <div className='overflow-x-scroll w-full flex items-center px-3 sm:px-10 whitespace-wrap space-x-8 sm:space-x-20 '>
        {allcategories.map((items)=>{
            return(
              <MainPageIcon 
              id={items.id}
              name={items.name}
              icon={items.icon}
              slug={items.slug}
            />)
          })}
        </div>
        </div>

        {navCtx.adsLoading === true ? <><h1 className='grid text-center'>Loading....</h1></> : <>{navCtx.setIconOnTrue === false ? <div className='grid sm:grid-cols-1 md:grid-cols-4 xl:grid-cols-5 gap-5 px-10 justify-center w-full mt-5'>
            {allads.map((items)=>{
              console.log(items.image)
              return(<MainPageAds 
                id={items.id}
                name={items.name}
                slug={items.slug}
                image={items.images[0]}
                images={items.images}
                description="Designed by Soren Sarup, PURAS..."
                date="Apr 1-8"
                price="513 night"
              />)
            })}
        </div> : <div className='grid sm:grid-cols-1 md:grid-cols-4 xl:grid-cols-5 gap-5 px-10 justify-center w-full mt-5'>
            {navCtx.ads.map((items)=>{
              console.log(items.image)
              return(<MainPageAds 
                id={items.id}
                name={items.name}
                slug={items.slug}
                image={items.images[0]}
                images={items.images}
                description="Designed by Soren Sarup, PURAS..."
                date="Apr 1-8"
                price="513 night"
              />)
            })}
        </div>}</>}
        


      </main>

      <footer className={styles.footer}>
      
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  const res = await axios.get(`http://localhost:5000/api/v1/categories`)
  const ads = await axios.get('http://localhost:5000/api/v1/ads')
  const allcategories = await res.data.data
  const allads = await ads.data.data

  
  return {
    props: {
      allcategories,
      allads
    }, // will be passed to the page component as props
  }
}

